# Services
version: "3.8"
services:
  # Nginx Service
  nginx:
    image: nginx:latest
    ports:
      - '80:80'
    # - '443:443'
    volumes:
      - ./websites/default/public:/websites/default/public
      - ./etc/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - php
    networks:
      - frontnet 
  php:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000"  
    volumes:
      - ./websites:/websites
      - ./php-logging.conf:/usr/local/etc/php-fpm.d/zz-log.conf
    depends_on:
      - mydb
    environment:
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_DATABASE
    networks:
      - frontnet
      - backnet
  mydb:
    container_name: mydb
    image: mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_DATABASE
    volumes:
      - mysqldata:/var/lib/mysql
    networks:
      - backnet  
  phpmyadmin:
    image: phpmyadmin:5.2.1
    container_name: poloadmin
    environment:
      PMA_HOST: mydb
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "8081:80"
    networks:
      - frontnet
      - backnet
    depends_on:
      - mydb    
volumes:
  mysqldata: {}
networks:
  frontnet:
    driver: bridge
  backnet:
    driver: bridge  