# Services
version: "3.8"
services:
  # Nginx Service
  nginx:
    image: nginx:latest
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./websites:/websites
      - ./nginx-conf:/etc/nginx/conf.d
    depends_on:
      - myphp
  php:
    container_name: myphp
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000"  
    volumes:
      - ./websites:/websites
      - ./php-logging.conf:/usr/local/etc/php-fpm.d/zz-log.conf
    depends_on:
      - mydb
    environment:
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_DATABASE
  mydb:
    container_name: mydb
    image: mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_DATABASE
    volumes:
      - mysqldata:/var/lib/mysql
# Volumes
volumes:
  mysqldata: {}
